baseURL = 'http://example.org/'
languageCode = 'ko-kr'
disableKinds = ["sitemap", "RSS"]
title = 'My New Hugo Site'
theme = "reveal-hugo"

[author]
name = "acts0z"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = false  # use highlight.js 
# codeFences = true  # use hugo highlighting at compile time
style = "tango"  # set a style for hugo highlighting

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true