baseURL = 'https://acts0z.github.io/'
languageCode = 'ko-kr'
disableKinds = ["sitemap", "RSS"]
title = '현주의 프리젠테이션'
theme = "reveal-hugo"
relativeURLs = true
uglyURLs = false

[author]
name = "acts0z"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = false  # use highlight.js 
# codeFences = true  # use hugo highlighting at compile time
style = "tango"  # set a style for hugo highlighting

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true